### PR TITLE
[Performance] Introduced a new lock for deallocation, so that both operations do not block each other

### PR DESCRIPTION
**Pull request by rahulbhawsar**
@bbottema  please review, below changes - 

I have observed that only a single lock is used for both allocation and deallocation operations. 

1. I have introduced a new lock, deallocateLock, which will be used for deallocation only. 
2. Since AutoAllocatorDeallocator - blocks to deallocate if not able to hold the lock,  I have moved them into separate threads, so that in case if allocation is not working, and all objects are claimed, at least deallocation should not be stopped.
3. Also, the expiry check is skipped if the policy set to Never expired. 

thanks,

### CODE REVIEW

**Comment by rahulbhawsar** [comment]
Hi @bbottema  - I have locally built this and tested it in my test env with a high load - 
I kept a ~30% suppressed emails during my testing to make sure connections would be added to the deallocation queue. 
I have tested this in 3 ad region with only ad1 having this fix. 
since each ad is having high number of threads trying to send emails - ad1 continues to do processing and completed processing the entire load, where ad2/3 ran into 421 - throttled and threads are stuck fighting for getting the connections.  ( this is the case with existing lib) 

I am sorry; I can't share the screenshot and detailed data points on processing and each ad's behavior.

**Comment by bbottema** [comment]
So what you're saying is: it works, please merge.

**Comment by rahulbhawsar** [comment]
Please review! if you see any review comments let me fix it.

**Comment by bbottema** [comment]
I had a quick look and it looks generally good to me. As I'm swamped right now and don't have the time to extensively test this myself, I had the new ChatGPT 4o have a look at the changes. Can you please address the concerns it raised?

> ### Specific Concerns:
> 1. invalidatePoolableObject Method: This method involves both claimLock and deallocateLock. It releases claimLock before acquiring deallocateLock, which could be problematic if another thread modifies the state in between these operations.
> 2. gatherExpiredObjects Method: This method iterates over available objects while holding claimLock. If allocation and deallocation are occurring simultaneously, this could lead to inconsistencies or missed updates.

**Comment by bbottema** [comment]
Possible new race conditions it identified:

image

**Comment by rahulbhawsar** [comment]
Please find the inputs below - 
### invalidatePoolableObject  method 
1. it's not modifying any state of the `claimedObject` rather  - a) changing value of `currentlyClaimed` and b) removing it from the `available`  both of them are guaded by the `claimLock` ( please note: where `deallocateLock` is only meant for when we are working with `waitingForDeallocation` 
2. so when we are calling the `addObjectforDeallocation` I am acquiring the `deallocateLock` and doing the operation. as below 
` private void addObjectForDeallocation(final PoolableObject<T> claimedObject) {

		deallocateLock.lock();
		try {
			waitingForDeallocation.add(claimedObject);
			claimedObject.setCurrentPoolStatus(PoolableObject.PoolStatus.WAITING_FOR_DEALLOCATION);
		} finally {
			deallocateLock.unlock();
		}
	}
`

### deallocationTriggering - 
this issue will not happen as claimedObject has already been removed from the `available` pool. it's only available in the `waitingForDeallocation` during addition we are holding the `deallocateLock` 

Please note: the race condition can only happen for the `claimedObject` when it is available even after adding it to the `waitingForDeallocation` which I don't see the case. 
we are not leaking the reference anywhere - even when it's claiming for use - allocation, we use claimLock and removes the claimedObject from the available pool. 
it's a false positive finding.

**Comment by bbottema** [comment]
Excellent, thank you for taking the time to have another look!

**Comment by bbottema** [comment]
Have you tried running the junit tests? The tests are [not](https://app.circleci.com/pipelines/github/bbottema/generic-object-pool/52/workflows/2bf975d2-597f-405c-9321-464aafd5e368/jobs/61) so happy.

**Comment by rahulbhawsar** [comment]
Yes, at my local all tests are passing. let me take a look at it why it's failing on CI
`
[INFO] Running TestApi
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/Users/rabhawsa/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.22.1/log4j-slf4j-impl-2.22.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.385 s - in TestApi
[INFO] Running org.bbottema.genericobjectpool.SimpleSingleObjectPoolTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.576 s - in org.bbottema.genericobjectpool.SimpleSingleObjectPoolTest
[INFO] Running org.bbottema.genericobjectpool.SimpleMultipleObjectPoolTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.077 s - in org.bbottema.genericobjectpool.SimpleMultipleObjectPoolTest
[INFO] Running org.bbottema.genericobjectpool.expirypolicies.TimeoutSinceCreationExpirationPolicyTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.633 s - in org.bbottema.genericobjectpool.expirypolicies.TimeoutSinceCreationExpirationPolicyTest
[INFO] Running org.bbottema.genericobjectpool.expirypolicies.CombinedExpirationPoliciesTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.038 s - in org.bbottema.genericobjectpool.expirypolicies.CombinedExpirationPoliciesTest
[INFO] Running org.bbottema.genericobjectpool.expirypolicies.TimeoutSinceLastAllocationExpirationPolicyTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.bbottema.genericobjectpool.expirypolicies.TimeoutSinceLastAllocationExpirationPolicyTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.1.0:jar (default-jar) @ generic-object-pool ---
[INFO] Building jar: /Users/rabhawsa/mygit/generic-object-pool/target/generic-object-pool-2.1.0.jar
[INFO] 
[INFO] --- source:3.0.1:jar-no-fork (attach-sources) @ generic-object-pool ---
[INFO] Building jar: /Users/rabhawsa/mygit/generic-object-pool/target/generic-object-pool-2.1.0-sources.jar
[INFO] 
[INFO] --- javadoc:3.1.1:jar (jar) @ generic-object-pool ---
[INFO] Skipping javadoc generation
[INFO] 
[INFO] --- license:3.0:remove (remove-licence-boilerplate-after-package) @ generic-object-pool ---
[INFO] 
[INFO] >>> spotbugs:3.1.12.2:check (default) > :spotbugs @ generic-object-pool >>>
[INFO] 
[INFO] --- spotbugs:3.1.12.2:spotbugs (spotbugs) @ generic-object-pool ---
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[INFO] 
[INFO] <<< spotbugs:3.1.12.2:check (default) < :spotbugs @ generic-object-pool <<<
[INFO] 
[INFO] 
[INFO] --- spotbugs:3.1.12.2:check (default) @ generic-object-pool ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.469 s
[INFO] Finished at: 2024-05-14T22:48:15+05:30
[INFO] ------------------------------------------------------------------------

`

**Comment by rahulbhawsar** [comment]
raised another PR to fix the test cases: https://github.com/bbottema/generic-object-pool/pull/7

**Pull request merged**
