### PR TITLE
Fixing test cases based on timing 

### PR DESCRIPTION
**Pull request by rahulbhawsar**
Hi @bbottema , sorry for delay in Pull Request - 
below are the changes done with explanation, when you have time, please review them and let me know if I need to fix any comments. 
**1.** I have observed that we were using expiration policy check two times - **a)** is to get check and collect expired Objects  **b)** check again and expire them. grouped into one function only. 
**2.**  when autoAllocation and Deallocation was in a single thread - it was sleeping for few ms, however, when I moved autoAllocator to a separate thread there was no sleep time, added it back. (please note: if no more allocations can be done take a few ms sleep and come back and check if pooled objects < pool size) 
**3.**  TestAPI test was failing,  due to timing issue, as Allocator and Deallocator are not any more part of same thread , they are working independently, hence making sure that we take some 30ms time and make sure that pool has come to a state which we want. 

thanks,  
Rahul

### CODE REVIEW

**Comment by bbottema** [comment]
Can you please summarize why we are doing this? I see you're slowing down the pool quite a bit. For SMTP connections it might not make a big difference, but if the object pool is being used for lighter weight objects, the added sleep adds a lot of overhead. What's the benefit of these changes?

**Comment by rahulbhawsar** [comment]
Hi @bbottema I acknowledge that (for a lightweight object it will be slow) , I have removed the allocator sleep, however , if you see the previous code - after allocation and deallocation there was a sleep of few ms. 
As of current code it's not needed. I have updated the PR. 
thanks,

**Comment by rahulbhawsar** [comment]
Hi @bbottema I have setup a circle ci , I could see one test is failing, let me look into it , will update the thread. (it could be a timing issue as its working fine on my local)

**Comment by rahulbhawsar** [comment]
Hi @bbottema  - I have looked into it, and found that we need a very minimal delay (added 5ms), for the following reasons - 

1. This delay is there as to allocate `claimLock` is required and to get a pooled object also `claimLock` is required.
2. in the test failure I have observed that  allocator is getting more number of times `claimLock` and other threads are not getting it  to get the pooledObject.  This I have observed while debugging the test cases where a certain number of threads needs to go into waitTimeout after not able to claim the object from pool .
Please note: above problem can be solved by having a fair ReentrantLock,  however, it will add a significant overhead as lock will maintain an internal queue for all the waiting threads. 
3. if you compare the behaviour with the previous code ( there was a delay in the common AutoAllocatorDeallocator) however, I have added a very small delay compare to previous delay) 

thanks,

**Comment by bbottema** [comment]
Released in 2.2.0!

**Comment by bbottema** [comment]
I may have to revert it after all. A downstream library, clustered-object-pool, doesn't build with the new version, producing ConcurrentModificationException.

**Comment by bbottema** [comment]
The junit test there fails consistently the same way. Perhaps you can have a look.

- GitHub: https://github.com/bbottema/clustered-object-pool
- Failing tests: https://app.circleci.com/pipelines/github/bbottema/clustered-object-pool/73/workflows/17d1c943-5bf2-40f2-9145-055a5d5d68f1/jobs/81

**Comment by rahulbhawsar** [comment]
hi @bbottema will fix it over the weekend. thank you!

**Comment by rahulbhawsar** [comment]
Hi @bbottema raised PR - https://github.com/bbottema/generic-object-pool/pull/8/commits

**Comment by bbottema** [comment]
Thank you for your effort!

I see you split up the method for determining expired objects and invalidating them into two methods, one for determining (collecting) expired objects and then in a new lock invalidating them.

Can shortly you explain why that solves the issue and why this was not an issue before your change to generic-object-pool? I'm trying to understanding the underlying cause of the exception.

**Comment by rahulbhawsar** [comment]
hi @bbottema - when I removed the double check of expired objects, I moved the logic into a single method - where it's checking for the expiry and in the loop only doing the invalidate(), however, doing the invalidate causes to change the state of `available` collection.  

and to do the expiry check, I was iterating this collection `available` hence this caused "ConcurrentModificationException".

to fix this I am iterating over `available` but not modifying it, only collecting expired objects and then in another function invalidating one by one.

**Pull request merged**
